### ISSUE TITLE
can not find file  scripts/extract_features.py

### ISSUE THREAD

**Issue by JackWhite-rwx** [davidmascharka/tbd-nets#15]
Excuse me,Thanks for your great work.when I run this code ,It have a little question.

"python scripts/extract_features.py \
    --input_image_dir </path/to/CLEVR/images/train> \
    --output_h5_file </path/to/train_features.h5> \
    --model_stage 2"

I can not find file  scripts/extract_features.py
could you help me?

**Comment by davidmascharka** [comment]
Hi Jack, we use Justin Johnson's processing script for this step; as we mention in [our readme](https://github.com/davidmascharka/tbd-nets#1-getting-data) we recommend cloning [his repo](https://github.com/facebookresearch/clevr-iep) and following [his steps for pre-processing the data](https://github.com/facebookresearch/clevr-iep/blob/master/TRAINING.md#preprocessing-clevr).

**Comment by davidmascharka** [comment]
Assuming this is resolved due to inactivity; please reopen if you need any additional help figuring this out
