### ISSUE TITLE
The environment setting

### ISSUE THREAD

**Issue by darkmir** [davidmascharka/tbd-nets#2]
I find that I am stuck with the environment settings. My system is Ubuntu 16.04 ,NVIDIA driver 384.111 cuda9.1 and GTX 1080 ti. 
But the error with step 2 is "Cuda runtime error(25):CUDA driver version is insufficient for CUDA runtime version". 
With the NVIDIA driver up to 387.26 or 390.42, Ubuntu cannot identity the NVIDIA driver. 
Nevertheless with CUDA version down to 8, the other ImportError libcudart.so.9.1: cannot open shared object files.
So may I ask what's the environment setting appropriate for the recreation?

**Comment by davidmascharka** [comment]
On Ubuntu 16.04 machines, we have CUDA driver versions 384.111, 387.34, and 390.25 all working with various versions of PyTorch and CUDA. Are you using the `environment.yml` file we provide, or are you using your own setup?

If you're not using our environment, what version of PyTorch are you running, and how did you install it? With the `ImportError`, I'm guessing PyTorch was built from source and linked against CUDA 9.1, but when you downgraded to CUDA 8, the `.so` files no longer exist so it can't find them.

I would double check that CUDA and the driver were correctly installed. Can you compile and run any of the NVIDIA samples?

**Comment by darkmir** [comment]
I use the environment set by myself and the version of Pytorch is 0.4.0a by https://github.com/pytorch/pytorch this direction.  So your guess is definitely right about it. 

And the ImportError is due to the CUDA 8. With reinstalling CUDA9.1 and recompiling pytorch, the ImportError is handled and the continuous problem is the Cuda runtime error(25).

After installing the NVIDIA driver384.111, I have tested the samples bandwidthtest and devideQuery. Both of them show the result = PASS. So is the idea "The cuda version9.1 is not appropriate for NVIDIA driver version 384.111" making sense??  

According to the directions provided, I will uninstall the pytorch, cuda 8.0, cuda 9.1 and set up a conda environment by that file for another try ?

**Comment by davidmascharka** [comment]
If you can build and run the NVIDIA samples, then I would guess PyTorch didn't install correctly. Try uninstalling and reinstalling that.

Alternatively, if you're using Anaconda, you can create a conda environment using our `environment.yml` file via:

``` shell
conda env create -f environment.yml
```

Then if you activate the environment with `source activate tbd-env` you should be able to run everything if the driver is installed correctly.

**Comment by davidmascharka** [comment]
@darkmir has the issue been resolved?

**Comment by darkmir** [comment]
@davidmascharka Certainly the tbd-env works!  With loading its own environments, the features extraction and question preprocessing have finished smoothly.

**Comment by davidmascharka** [comment]
Great!
