### ISSUE TITLE
How to evaluate test results?

### ISSUE THREAD

**Issue by lwye** [davidmascharka/tbd-nets#4]
Hi,
After getting predicted answers for test data, how can I evaluate results?
Since there are different setting in your paper (e.g., Count, Compare, Exist, and so on), could u have code snippet to conveniently achieve this?
Thanks

**Comment by davidmascharka** [comment]
[Justin Johnson](https://cs.stanford.edu/people/jcjohns/) has the test answers, so you would need to get in touch with him to get test results. He uses [this script](https://gist.github.com/jcjohnson/5796ff43e67835cb8e1de882a5867994) to evaluate the predictions. You could do the same thing for validation results if you're interested in that breakdown as well.

**Comment by lwye** [comment]
I see. Thanks for your reply!

**Comment by lwye** [comment]
BTW, are these results reported in Table 2 of your paper for validation or test set?

**Comment by davidmascharka** [comment]
Those numbers are on the test set. You should observe similar performance on the validation data though.
