### ISSUE TITLE
tensor matches error

### ISSUE THREAD

**Issue by bidongqinxian** [davidmascharka/tbd-nets#6]
My `eval.py`  file copies from `test-eval.ipynb`
```
import torch

from pathlib import Path
import numpy as np
import h5py

from tbd.module_net import load_tbd_net
from utils.clevr import load_vocab
from utils.generate_programs import load_program_generator, generate_programs


vocab_path = Path('data/vocab.json')
model_path = Path('models/clevr-reg-hres.pt')
tbd_net = load_tbd_net(model_path, load_vocab(vocab_path))


program_generator = load_program_generator(Path('models/program_generator.pt'))
generate_programs(Path('data/val_questions.h5'), program_generator, 
                  dest_dir=Path('data/val/'), batch_size=128)


use_np_features = False
if use_np_features:
    features = np.load(str(Path('data/val/val_features.npy')), mmap_mode='r')
else:
    features = h5py.File(Path('data/val_features.h5'))['features']

question_np = np.load(Path('data/val/questions.npy'))
image_idx_np = np.load(Path('data/val/image_idxs.npy'))
programs_np = np.load(Path('data/val/programs.npy'))


answers = ['blue', 'brown', 'cyan', 'gray', 'green', 'purple', 'red', 'yellow',
           'cube', 'cylinder', 'sphere',
           'large', 'small',
           'metal', 'rubber',
           'no', 'yes',
           '0', '1', '10', '2', '3', '4', '5', '6', '7', '8', '9']

pred_idx_to_token = dict(zip(range(len(answers)), answers))


f = open('predicted_answers.txt', 'w')
def write_preds(preds):
    for pred in preds:
        f.write(pred)
        f.write('\n')



device = 'cuda' if torch.cuda.is_available() else 'cpu'



batch_size = 128
for batch in range(0, len(programs_np), batch_size):
    image_idx = image_idx_np[batch:batch+batch_size]
    programs = torch.LongTensor(programs_np[batch:batch+batch_size]).to(device)
    
    if use_np_features:
        feats = torch.FloatTensor(np.asarray(features[image_idx])).to(device)
    else:
        # Using HDF5 files requires some overhead due to constraints on how those may
        # be accessed. We cannot index into the file using a numpy array. We also cannot 
        # access the same element multiple times (e.g. we cannot index into an h5py.File 
        # with [1,1,1]) because we are constrained to increasing sequences
        feats = []
        for idx in image_idx:
            feats.append(np.asarray(features[idx]))
        feats = torch.FloatTensor(np.asarray(feats)).to(device)

    outputs = tbd_net(feats, programs)
    _, preds = outputs.max(1)
    preds = [pred_idx_to_token[pred] for pred in preds.detach().to('cpu').numpy()]
    write_preds(preds)
f.close()
```
and error as 
```
Traceback (most recent call last):
  File "eval.py", line 72, in <module>
    outputs = tbd_net(feats, programs)
  File "/home/dengwei/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dengwei/tbd-nets/tbd/module_net.py", line 195, in forward
    output = module(feat_input, output)
  File "/home/dengwei/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dengwei/tbd-nets/tbd/modules.py", line 92, in forward
    attended_feats = torch.mul(feats, attn.repeat(1, self.dim, 1, 1))
RuntimeError: The size of tensor a (128) must match the size of tensor b (16384) at non-singleton dimension 1
```
maybe I should use NUMPY file rather HDF5 file?I extract feature from [this master](https://github.com/facebookresearch/clevr-iep/blob/master/TRAINING.md#preprocessing-clevr).

**Comment by davidmascharka** [comment]
Can you add this line right before you loop through the data?

``` python
print(programs[12])
```

You should get out

```
tensor([ 10,  39,  43,  19,  24,  41,   2,   2,   2,  24,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0], device='cuda:0')
```

The issue here is that the program generator has produced a bad program. The question this corresponds to is: "How many metallic objects are big blue cubes or blue objects?" and the program that is produced is:

```
'exist',
 'same_shape',
 'unique',
 'filter_material[metal]',
 'filter_size[large]',
 'scene',
 '<END>',
 '<END>',
 '<END>',
 'filter_size[large]',
```

It's not clear to me why the program generator does so poorly here, but the way we're forwarding input through the model does not handle this case properly. It's fixable by restructuring the way we're handling input, but we'd prefer not to change our logic to handle that. Another possibility would be inspecting the programs to ensure they are, in fact, valid before sending them through the model.

This is a good catch; the program generator is nearly perfect, but this is just a case in which it clearly goes severely wrong. We never ran into this because we didn't use our program generator on the validation data and it doesn't make this sort of mistake on the test data.

Edit: It appears not to be an issue isolated to that question. Further, that question *should* be easy for the program generator to parse correctly. I'll take a closer look at this later and get back to you.

**Comment by bidongqinxian** [comment]
yes, I got this outcome as:
```
dengwei@ubuntu:~/tbd-nets$ python eval.py
Generating programs...
Saved programs as /home/dengwei/tbd-nets/data/val/programs.npy
Saved image indices as /home/dengwei/tbd-nets/data/val/image_idxs.npy
Saved questions as /home/dengwei/tbd-nets/data/val/questions.npy
tensor([ 10,  39,  43,  19,  24,  41,   2,   2,   2,  24,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0], device='cuda:0')
```
 @davidmascharka

**Comment by davidmascharka** [comment]
@bidongqinxian thanks for verifying, and for catching this! My `generate_programs` function was translated incorrectly from Justin Johnson's model. The updated code from b8d637623f7daa5a71ef710af79052855088b9eb should work properly now. If you could pull master and verify, it would be much appreciated.

**Comment by bidongqinxian** [comment]
I don't know whether the bug exists, but it's too slow to generate programs(I spent a few hours to run ``eval.py`` but output nothing indeed,the interface still remained "Generating programs..." ),and I'm sure it is running.

**Comment by davidmascharka** [comment]
It's certainly slower, but it shouldn't be on the order of hours. The modification would be to rewrite `generate_programs` to better match Justin's code, rather than make calls to `reinforce_sample` for each individual question. Batching is substantially faster. You could add a printout every 100 iterations or so just to see progress. 

What hardware are you working with? I was able to finish generating programs on a GTX 1080Ti within 20-30 minutes or so, which seemed reasonable as it's a one-time cost and should be cached for any future runs. This isn't a priority for us, since we only need to do this once for test data and the natural-language component isn't the focus of our work.

**Comment by bidongqinxian** [comment]
Hi, the error still exists as the initial one. And before this error, another error as:
```
/home/dengwei/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
i =[10 39 43 19 24 41  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0]
Traceback (most recent call last):
  File "eval.py", line 72, in <module>
    outputs = tbd_net(feats, programs)
  File "/home/dengwei/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dengwei/tbd-nets/tbd/module_net.py", line 180, in forward
    module_type = self.vocab['program_idx_to_token'][i]
TypeError: unhashable type: 'numpy.ndarray'
```
I changed the code as(from line 177 to 182 in ``module_net.py``):
```
for i in reversed(programs.data[n].cpu().numpy()):
                #print('i =' % i)
                for a,b in enumerate(i):
                    module_type = self.vocab['program_idx_to_token'][b]
                    if module_type in {'<NULL>', '<START>', '<END>', '<UNK>', 'unique'}:
                        continue  # the above are no-ops in our model
```
the error disappeared, is it right? 
@davidmascharka

**Comment by davidmascharka** [comment]
That error would happen if the `generate_programs` function wasn't squeezing the outputs properly. My commit did something weird, so I pushed again. [Line 256 of `generate_programs`](https://github.com/davidmascharka/tbd-nets/blob/master/utils/generate_programs.py#L256) should squeeze the data before appending it to the list.

**Comment by bidongqinxian** [comment]
Thanks for informing that ,I learned a lot. I changed the code to ``progs.append(program.cpu().numpy().squeeze())``, and I removed ``for a,b in enumerate(i)``. When I ran the ``eval.py`` around 15 minutes, the error occured again
```
Traceback (most recent call last):
  File "eval.py", line 72, in <module>
    outputs = tbd_net(feats, programs)
  File "/home/dengwei/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dengwei/tbd-nets/tbd/module_net.py", line 200, in forward
    output = module(feat_input, output)
  File "/home/dengwei/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dengwei/tbd-nets/tbd/modules.py", line 127, in forward
    attended_feats = torch.mul(feats, attn.repeat(1, self.dim, 1, 1))
RuntimeError: The size of tensor a (128) must match the size of tensor b (16384) at non-singleton dimension 1
```
I printed out the ``final_module_outputs`` of ``module_net.py `` in line 202, I found these
```
tensor([[[[  0.1177,   0.0639,   0.2034,  ...,   0.1145,   0.0676,
             0.0706],
          [  0.1654,   0.3045,   0.4034,  ...,   0.2383,   0.0803,
             0.2134],
          [  0.1039,   0.1023,   0.3015,  ...,   0.1826,   0.0778,
             0.1604],
          ...,
          [  0.1722,   0.0000,   0.1147,  ...,   0.0000,   0.0000,
             0.1538],
          [  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0000,
             0.0882],
          [  0.0659,   0.0765,   0.2080,  ...,   0.0000,   0.0000,
             0.4016]],

         [[  0.0000,   0.0621,   0.0000,  ...,   0.0992,   0.0702,
             0.1408],
          [  0.0000,   0.0000,   0.0000,  ...,   0.0000,   0.0564,
             0.1429],
          [  0.0917,   0.1845,   0.0000,  ...,   0.1301,   0.1111,
             0.1944],
          ...,
          [  0.0250,   0.2981,   0.0449,  ...,   0.2866,   0.0776,
             0.0739],
          [  0.0000,   0.0000,   0.0000,  ...,   0.2916,   0.0967,
             0.2125],
          [  0.0000,   0.0000,   0.0000,  ...,   0.0334,   0.1566,
             0.0104]],
```
and so on
those proved the code can run. Maybe something broken?

**Comment by davidmascharka** [comment]
I'm not sure what happened, but it looks like you're not up-to-date with the current master. The error message you posted says that the code fails on `module_net.py` line 200 and mentions the call is `output = module(feat_input, output)`. However, [Line 200](https://github.com/davidmascharka/tbd-nets/blob/master/tbd/module_net.py#L200) doesn't contain that function call.

I'm not quite sure what `enumerate` call you removed; the only call to `enumerate` we make in this repository is in `full-vqa-example.ipynb`, which should be completely unrelated to what you're trying to run here.

I would recommend you clone the repository fresh to verify everything on your end matches what I have. I've successfully generated programs for the validation set as you're attempting to do and been able to run them all through the `tbd_net` instance.

**Comment by bidongqinxian** [comment]
Ok ，maybe I will download the latest master and run the code again. Thanks for your advice!
